Blacklist = ['HARRY POTTER', 'RON WEASLEY', 'HERMIONE GRANGER', 'NEVILLE LONGBOTTOM', 'ALBUS DUMBLEDORE',
             'SEVERUS SNAPE', 'SIRIUS BLACK', 'DRACO MALFOY', 'TOM RIDDLE', 'GILDEROY LOCKHART',
             'DOLORES UMBRIDGE', 'BATHILDA BAGSHOT', 'BELLATRIX LESTRANGE', 'SUSAN BONES', 'LAVENDER BROWN',
             'CHO CHANG', 'COLIN CREEVY', 'VERNON DURSLEY', 'LUNA LOVEGOOD', 'RUBEUS HAGRID']